controllers/AdminController.php
<?php
/**
 * AdminController
 * @var $this ommu\archive\controllers\AdminController
 * @var $model ommu\archive\models\Archives
 *
 * AdminController implements the CRUD actions for Archives model.
 * Reference start
 * TOC :
 *	Index
 *	Manage
 *	Create
 *	Update
 *	View
 *	Delete
 *	RunAction
 *	Publish
 *	Location
 *	ResetLocation
 *	Preview
 *	Import
 *
 *	findModel
 *
 * @author Putra Sudaryanto <putra@ommu.id>
 * @contact (+62)811-2540-432
 * @copyright Copyright (c) 2019 OMMU (www.ommu.id)
 * @created date 3 October 2019, 16:06 WIB
 * @link https://bitbucket.org/ommu/archive-mediakases
 *
 */

namespace ommu\archive\controllers;

use Yii;
use app\components\Controller;
use mdm\admin\components\AccessControl;
use yii\filters\VerbFilter;
use ommu\archive\models\Archives;
use ommu\archive\models\search\Archives as ArchivesSearch;
use ommu\archive\models\ArchiveSetting;
use yii\web\UploadedFile;
use ommu\archiveLocation\models\ArchiveLocations;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use thamtech\uuid\helpers\UuidHelper;

class AdminController extends Controller
{
	use \ommu\traits\FileTrait;

	/**
	 * {@inheritdoc}
	 */
	public function init()
	{
        parent::init();

        if (Yii::$app->request->get('id')) {
            if ($this->isArchive() == true) {
                $this->subMenu = $this->module->params['archive_submenu'];
            } else {
                $this->subMenu = $this->module->params['fond_submenu'];
            }
        }

		$setting = ArchiveSetting::find()
			->select(['breadcrumb_param'])
			->where(['id' => 1])
			->one();
		$this->breadcrumbApp = $setting->breadcrumb;
		$this->breadcrumbAppParam = $setting->getBreadcrumbAppParam();
	}

	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
        return [
            'access' => [
                'class' => AccessControl::className(),
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'publish' => ['POST'],
                ],
            ],
        ];
	}

	/**
	 * {@inheritdoc}
	 */
	public function actionIndex()
	{
        return $this->redirect(['manage']);
	}

	/**
	 * Lists all Archives models.
	 * @return mixed
	 */
	public function actionManage()
	{
        $searchModel = new ArchivesSearch(['isArchive' => $this->isArchive()]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $gridColumn = Yii::$app->request->get('GridColumn', null);
        $cols = [];
        if ($gridColumn != null && count($gridColumn) > 0) {
            foreach ($gridColumn as $key => $val) {
                if ($gridColumn[$key] == 1) {
                    $cols[] = $key;
                }
            }
        }
        $columns = $searchModel->getGridColumn($cols);

        if (($type = Yii::$app->request->get('type')) != null) {
            $type = \ommu\archive\models\ArchiveType::findOne($type);
        }
        if (($unit = Yii::$app->request->get('unit')) != null) {
            $unit = \ommu\archive\models\ArchiveUnit::findOne($unit);
        }
        if (($fond = Yii::$app->request->get('fond')) != null) {
            $fond = \ommu\archive\models\Archives::findOne($fond);
			$fond->isArchive = false;
			$attributes = [
				'archive_name' => Yii::t('app', 'Title')
			];
			$fond->setAttributeLabels($attributes);
		}

		$this->view->title = !$this->isArchive() ? Yii::t('app', 'Archive Lists') : Yii::t('app', 'Archives');
		$this->view->description = '';
		$this->view->keywords = '';
		return $this->render('admin_manage', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
			'columns' => $columns,
			'type' => $type,
			'unit' => $unit,
			'fond' => $fond,
			'isArchive' => $this->isArchive(),
		]);
	}

	/**
	 * Creates a new Archives model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate()
	{
        $model = new Archives(['isArchive' => $this->isArchive()]);
        if (!$model->isArchive) {
			$attributes = [
				'archive_name' => Yii::t('app', 'Title')
			];
			$model->setAttributeLabels($attributes);
		}
		$setting = ArchiveSetting::find()
			->select(['field', 'item_preview_type', 'item_file_type'])
			->where(['id' => 1])
            ->one();

        if (Yii::$app->request->isPost) {
            $postData = Yii::$app->request->post();
            $model->load($postData);
            $model->item_define = $postData['item_define'] ? $postData['item_define'] : 0;
            $model->item_preview = UploadedFile::getInstance($model, 'item_preview');
            if (!($model->item_preview instanceof UploadedFile && !$model->item_preview->getHasError())) {
                $model->item_preview = $postData['item_preview'] ? $postData['item_preview'] : '';
            }
			$model->item_file = UploadedFile::getInstance($model, 'item_file');
            if (!($model->item_file instanceof UploadedFile && !$model->item_file->getHasError())) {
                $model->item_file = $postData['item_file'] ? $postData['item_file'] : '';
            }

            if ($model->save()) {
                Yii::$app->session->setFlash('success', Yii::t('app', '{label} success created.', ['label' => !$model->isArchive ? Yii::t('app', 'Archive list') : Yii::t('app', 'Archive')]));

                if (!$model->backToManage) {
                    if (!Yii::$app->request->isAjax) {
						return $this->redirect(['create']);
                    }
					return $this->redirect(Yii::$app->request->referrer ?: ['create']);
				}
                if (!Yii::$app->request->isAjax) {
                    return $this->redirect(['manage']);
                }
                return $this->redirect(Yii::$app->request->referrer ?: ['manage']);

            } else {
                if (Yii::$app->request->isAjax) {
                    return \yii\helpers\Json::encode(\app\components\widgets\ActiveForm::validate($model));
                }
            }
        }

		$this->view->title = Yii::t('app', 'Create {label}', ['label' => !$model->isArchive ? Yii::t('app', 'Archive List') : Yii::t('app', 'Archive')]);
		$this->view->description = '';
		$this->view->keywords = '';
		return $this->oRender('admin_create', [
			'model' => $model,
			'setting' => $setting,
		]);
	}

	/**
	 * Updates an existing Archives model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);
		$setting = ArchiveSetting::find()
			->select(['field', 'item_preview_type', 'item_file_type'])
			->where(['id' => 1])
            ->one();

        if (Yii::$app->request->isPost) {
            $postData = Yii::$app->request->post();
            $model->load($postData);
            $model->item_define = $postData['item_define'] ? $postData['item_define'] : 0;
            $model->item_preview = UploadedFile::getInstance($model, 'item_preview');
            $model->item_file = UploadedFile::getInstance($model, 'item_file');

            if ($model->save()) {
                Yii::$app->session->setFlash('success', Yii::t('app', '{label} success updated.', ['label' => !$model->isArchive ? Yii::t('app', 'Archive list') : Yii::t('app', 'Archive')]));

                if (!$model->backToManage) {
                    if (!Yii::$app->request->isAjax) {
						return $this->redirect(['update', 'id' => $model->id]);
                    }
					return $this->redirect(Yii::$app->request->referrer ?: ['update', 'id' => $model->id]);
				}
                if (!Yii::$app->request->isAjax) {
                    return $this->redirect(['manage']);
                }
                return $this->redirect(Yii::$app->request->referrer ?: ['manage']);

            } else {
                if (Yii::$app->request->isAjax) {
                    return \yii\helpers\Json::encode(\app\components\widgets\ActiveForm::validate($model));
                }
            }
        }

        $this->subMenuParam = $model->id;
		$this->view->title = Yii::t('app', 'Update {label}: {archive-name}', ['label' => !$model->isArchive ? Yii::t('app', 'Archive List') : Yii::t('app', 'Archive'), 'archive-name' => $model::htmlHardDecode($model->archive_name)]);
		$this->view->description = '';
		$this->view->keywords = '';
		return $this->oRender('admin_update', [
			'model' => $model,
			'setting' => $setting,
		]);
	}

	/**
	 * Displays a single Archives model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
        $model = $this->findModel($id);

        $this->subMenuParam = $model->id;
		$this->view->cards = false;
		$this->view->title = Yii::t('app', 'Detail {label}: {archive-name}', ['label' => !$model->isArchive ? Yii::t('app', 'Archive List') : Yii::t('app', 'Archive'), 'archive-name' => $model::htmlHardDecode($model->archive_name)]);
		$this->view->description = '';
		$this->view->keywords = '';
		return $this->oRender('admin_view', [
			'model' => $model,
			'small' => false,
		]);
	}

	/**
	 * Deletes an existing Archives model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		$model = $this->findModel($id);
		$model->publish = 2;

        if ($model->save(false, ['publish', 'modified_id'])) {
			Yii::$app->session->setFlash('success', Yii::t('app', '{label} success deleted.', ['label' => !$model->isArchive ? Yii::t('app', 'Archive list') : Yii::t('app', 'Archive')]));
			return $this->redirect(Yii::$app->request->referrer ?: ['manage']);
		}
	}

	/**
	 * actionPublish an existing Archives model.
	 * If publish is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */

views/view/history/_option_form.php
<?php
/**
 * Archive View Histories (archive-view-history)
 * @var $this app\components\View
 * @var $this ommu\archive\controllers\view\HistoryController
 * @var $model ommu\archive\models\search\ArchiveViewHistory
 * @var $form yii\widgets\ActiveForm
 *
 * @author Putra Sudaryanto <putra@ommu.id>
 * @contact (+62)811-2540-432
 * @copyright Copyright (c) 2020 OMMU (www.ommu.id)
 * @created date 25 February 2020, 16:43 WIB
 * @link https://bitbucket.org/ommu/archive-mediakases
 *
 */

use yii\helpers\Html;
use yii\helpers\Url;

$js = <<<JS
	$('form[name="gridoption"] :checkbox').click(function() {
		var url = $('form[name="gridoption"]').attr('action');
		var data = $('form[name="gridoption"] :checked').serialize();
		$.ajax({
			url: url,
			data: data,
			success: function(response) {
				//$("#w0").yiiGridView("applyFilter");
				//$.pjax({container: '#w0'});
				return false;
			}
		});
	});
JS;
	$this->registerJs($js, \app\components\View::POS_READY);
?>

<div class="grid-form">
    <?php echo Html::beginForm(Url::to(['/'.$route]), 'get', ['name' => 'gridoption']);
        $columns = [];
        foreach ($model->templateColumns as $key => $column) {
            if ($key == '_no') {
                continue;
            }
            $columns[$key] = $key;
        }
    ?>
        <ul>
            <?php foreach ($columns as $key => $val) { ?>
            <li>
				<?php echo Html::checkBox(sprintf("GridColumn[%s]", $key), in_array($key, $gridColumns) ? true : false, ['id' => 'GridColumn_'.$key]); ?>
				<?php echo Html::label($model->getAttributeLabel($val), 'GridColumn_'.$val); ?>
            </li>
            <?php } ?>
        </ul>
    <?php echo Html::endForm(); ?>
</div>

views/view/history/_search.php
<?php
/**
 * Archive View Histories (archive-view-history)
 * @var $this app\components\View
 * @var $this ommu\archive\controllers\view\HistoryController
 * @var $model ommu\archive\models\search\ArchiveViewHistory
 * @var $form yii\widgets\ActiveForm
 *
 * @author Putra Sudaryanto <putra@ommu.id>
 * @contact (+62)811-2540-432
 * @copyright Copyright (c) 2020 OMMU (www.ommu.id)
 * @created date 25 February 2020, 16:43 WIB
 * @link https://bitbucket.org/ommu/archive-mediakases
 *
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<div class="archive-view-history-search search-form">

	<?php $form = ActiveForm::begin([
		'action' => ['index'],
		'method' => 'get',
		'options' => [
			'data-pjax' => 1
		],
	]); ?>

		<?php echo $form->field($model, 'archiveName');?>

		<?php echo $form->field($model, 'view_date')
			->input('date');?>

		<?php echo $form->field($model, 'view_ip');?>

		<div class="form-group">
			<?php echo Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']); ?>
			<?php echo Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']); ?>
		</div>

	<?php ActiveForm::end(); ?>

</div>

views/view/history/admin_manage.php
<?php
/**
 * Archive View Histories (archive-view-history)
 * @var $this app\components\View
 * @var $this ommu\archive\controllers\view\HistoryController
 * @var $model ommu\archive\models\ArchiveViewHistory
 * @var $searchModel ommu\archive\models\search\ArchiveViewHistory
 *
 * @author Putra Sudaryanto <putra@ommu.id>
 * @contact (+62)811-2540-432
 * @copyright Copyright (c) 2020 OMMU (www.ommu.id)
 * @created date 25 February 2020, 16:43 WIB
 * @link https://bitbucket.org/ommu/archive-mediakases
 *
 */

use yii\helpers\Html;
use yii\helpers\Url;
use app\components\grid\GridView;
use yii\widgets\Pjax;

$context = $this->context;
if ($context->breadcrumbApp) {
    $this->params['breadcrumbs'][] = ['label' => $context->breadcrumbAppParam['name'], 'url' => [$context->breadcrumbAppParam['url']]];
}
if ($view != null) {
    $this->params['breadcrumbs'][] = ['label' => $view->archive->isArchive ? Yii::t('app', 'Archive') : Yii::t('app', 'Archive List'), 'url' => $view->archive->isArchive ? ['admin/index'] : ['book/index']];
    $this->params['breadcrumbs'][] = ['label' => $view->archive->isArchive ? $view::htmlHardDecode($view->archive->archive_name) : $view->archive->fond_code, 'url' => [($view->archive->isArchive ? 'admin' : 'book').'/view', 'id' => $view->archive_id]];
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'View'), 'url' => ['view/admin/manage', 'archive' => $view->archive_id]];
} else {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Archive'), 'url' => ['/admin/index']];
}
$this->params['breadcrumbs'][] = $this->title;

$this->params['menu']['option'] = [
	//['label' => Yii::t('app', 'Search'), 'url' => 'javascript:void(0);'],
	['label' => Yii::t('app', 'Grid Option'), 'url' => 'javascript:void(0);'],
];
?>

<div class="archive-view-history-manage">
<?php Pjax::begin(); ?>

<?php if ($view != null) {
    echo $this->render('/view/admin/admin_view', ['model' => $view, 'small' => true]);
} ?>

<?php if ($archive != null) {
    echo $this->render('/admin/admin_view', ['model' => $archive, 'small' => true]);
} ?>

<?php //echo $this->render('_search', ['model' => $searchModel]); ?>

<?php echo $this->render('_option_form', ['model' => $searchModel, 'gridColumns' => $searchModel->activeDefaultColumns($columns), 'route' => $this->context->route]); ?>

<?php
$columnData = $columns;
array_push($columnData, [
	'class' => 'app\components\grid\ActionColumn',
	'header' => Yii::t('app', 'Option'),
	'urlCreator' => function($action, $model, $key, $index) {
        if ($action == 'view') {
            return Url::to(['view', 'id' => $key]);
        }
        if ($action == 'update') {
            return Url::to(['update', 'id' => $key]);
        }
        if ($action == 'delete') {
            return Url::to(['delete', 'id' => $key]);
        }
	},
	'buttons' => [
		'view' => function ($url, $model, $key) {
			return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, ['title' => Yii::t('app', 'Detail'), 'class' => 'modal-btn']);
		},
		'update' => function ($url, $model, $key) {
			return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, ['title' => Yii::t('app', 'Update'), 'class' => 'modal-btn']);
		},
		'delete' => function ($url, $model, $key) {
			return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
				'title' => Yii::t('app', 'Delete'),
				'data-confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
				'data-method'  => 'post',
			]);
		},
	],
	'template' => '{view} {delete}',
]);

echo GridView::widget([
	'dataProvider' => $dataProvider,
	'filterModel' => $searchModel,
	'columns' => $columnData,
]); ?>

<?php Pjax::end(); ?>
</div>

views/view/history/admin_view.php
<?php
/**
 * Archive View Histories (archive-view-history)
 * @var $this app\components\View
 * @var $this ommu\archive\controllers\view\HistoryController
 * @var $model ommu\archive\models\ArchiveViewHistory
 *
 * @author Putra Sudaryanto <putra@ommu.id>
 * @contact (+62)811-2540-432
 * @copyright Copyright (c) 2020 OMMU (www.ommu.id)
 * @created date 25 February 2020, 16:43 WIB
 * @link https://bitbucket.org/ommu/archive-mediakases
 *
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

if (!$small) {
    $context = $this->context;
    if ($context->breadcrumbApp) {
        $this->params['breadcrumbs'][] = ['label' => $context->breadcrumbAppParam['name'], 'url' => [$context->breadcrumbAppParam['url']]];
    }
    $this->params['breadcrumbs'][] = ['label' => $model->view->archive->isArchive ? Yii::t('app', 'Archive') : Yii::t('app', 'Archive List'), 'url' => $model->view->archive->isArchive ? ['admin/index'] : ['book/index']];
    $this->params['breadcrumbs'][] = ['label' => $model->view->archive->isArchive ? $model->view::htmlHardDecode($model->view->archive->archive_name) : $model->view->archive->fond_code, 'url' => [($model->view->archive->isArchive ? 'admin' : 'book').'/view', 'id' => $model->view->archive_id]];
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'View'), 'url' => ['view/admin/manage', 'archive' => $model->view->archive_id]];
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'History'), 'url' => ['view/history/manage', 'view' => $model->view_id]];
    $this->params['breadcrumbs'][] = Yii::t('app', 'Detail');

    $this->params['menu']['content'] = [
        ['label' => Yii::t('app', 'Delete'), 'url' => Url::to(['delete', 'id' => $model->id]), 'htmlOptions' => ['data-confirm' => Yii::t('app', 'Are you sure you want to delete this item?'), 'data-method' => 'post', 'class' => 'btn btn-danger'], 'icon' => 'trash'],
    ];
} ?>

<div class="archive-view-history-view">

<?php
$attributes = [
	[
		'attribute' => 'id',
		'value' => $model->id ? $model->id : '-',
		'visible' => !$small,
	],
	[
		'attribute' => 'archiveName',
		'value' => function ($model) {
			$archiveName = isset($model->view->archive) ? $model->view->archive->archive_name : '-';
            if ($archiveName != '-') {
                return Html::a($archiveName, ['admin/view', 'id' => $model->view->archive_id], ['title' => $model->view::htmlHardDecode($archiveName), 'class' => 'modal-btn']);
            }
			return $archiveName;
		},
		'format' => 'html',
	],
	[
		'attribute' => 'view.user_id',
		'value' => isset($model->view->user) ? $model->view->user->displayname : '-',
	],
	[
		'attribute' => 'view_date',
		'value' => Yii::$app->formatter->asDatetime($model->view_date, 'medium'),
		'visible' => !$small,
	],
	[
		'attribute' => 'view_ip',
		'value' => $model->view_ip,
		'visible' => !$small,
	],
];

echo DetailView::widget([
	'model' => $model,
	'options' => [
		'class' => 'table table-striped detail-view',
	],
	'attributes' => $attributes,
]); ?>

</div>